In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install pymupdf

Collecting pymupdf
  Downloading pymupdf-1.28.2-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (26 kB)
Downloading pymupdf-1.28.2-cp310-abi3-manylinux_2_28_x86_64.whl (25.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 44.6 MB/s eta 0:00:00
Installing collected packages: pymupdf
Successfully installed pymupdf-1.28.2

In [3]:
import os
from pathlib import Path
import fitz  # PyMuPDF

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

In [4]:
PROJECT_PATH = Path("/content/drive/MyDrive/uterine-emg-rag")

PAPERS_PATH = PROJECT_PATH / "papers"

print(PAPERS_PATH)

/content/drive/MyDrive/uterine-emg-rag/papers

In [5]:
print(PAPERS_PATH.exists())

True

In [6]:
pdf_files = sorted(PAPERS_PATH.glob("*.pdf"))

print(f"Found {len(pdf_files)} PDFs\n")

for pdf in pdf_files:
    print(pdf.name)

Found 10 PDFs

paper1.pdf
paper10.pdf
paper2.pdf
paper3.pdf
paper4.pdf
paper5.pdf
paper6.pdf
paper7.pdf
paper8.pdf
paper9.pdf

In [7]:
def extract_text(pdf_path):

    document = fitz.open(pdf_path)

    text = ""

    for page in document:

        text += page.get_text()

    document.close()

    return text

In [8]:
sample_text = extract_text(pdf_files[0])

print(sample_text[:1500])

Contents lists available at ScienceDirect
Artificial Intelligence In Medicine
journal homepage: www.elsevier.com/locate/artmed

Electrohysterography in modern obstetrics: Advances in signal processing,
machine learning, and clinical applications
Katerina Barnova a,b
, Radek Martinek a
, Jitka Horakova c, Ondrej Simetka c
,
Radana Vilimkova Kahankova a
,∗
a VSB – Technical University of Ostrava, Department of Cybernetics and Biomedical Engineering, 17. listopadu 2172/15, Ostrava, 70800, Czechia
b Hospital AGEL Trinec-Podlesi, Telemedicine Center, Konska 453, Trinec, 739 61, Czechia
c University Hospital Ostrava, Department of Obstetrics and Gynecology, 17. listopadu 1790/5, Ostrava, 708 00, Czechia
A R T I C L E  I N F O
Keywords:
Uterine electromyography
Uterine activity monitoring
EHG signal processing
Uterine contractions detection
Term/preterm birth prediction
Pregnancy/labor classification

A B S T R A C T
Electrohysterography (EHG) represents a promising computational approach for non-invasive monitoring of
uterine activity during pregnancy and labor. This review summarizes the advancements in signal processing
techniques and machine learning algorithms that have been applied to enhance the utility of EHG. Key topics
include the extraction and analysis of uterine electrical signals, classification of contractions, and prediction
of obstetric outcomes such as preterm and labor/non-labor states. The review emphasizes computational
methodologies for signal proces

In [9]:
len(sample_text.split())

24185

In [10]:
papers = {}

In [11]:
for pdf in pdf_files:

    text = extract_text(pdf)

    papers[pdf.stem] = text

In [12]:
print(len(papers))

10

In [13]:
papers.keys()

dict_keys(['paper1', 'paper10', 'paper2', 'paper3', 'paper4', 'paper5', 'paper6', 'paper7', 'paper8', 'paper9'])

In [15]:
print(papers["paper1"][:1500])

Contents lists available at ScienceDirect
Artificial Intelligence In Medicine
journal homepage: www.elsevier.com/locate/artmed

Electrohysterography in modern obstetrics: Advances in signal processing,
machine learning, and clinical applications
Katerina Barnova a,b
, Radek Martinek a
, Jitka Horakova c, Ondrej Simetka c
,
Radana Vilimkova Kahankova a
,∗
a VSB – Technical University of Ostrava, Department of Cybernetics and Biomedical Engineering, 17. listopadu 2172/15, Ostrava, 70800, Czechia
b Hospital AGEL Trinec-Podlesi, Telemedicine Center, Konska 453, Trinec, 739 61, Czechia
c University Hospital Ostrava, Department of Obstetrics and Gynecology, 17. listopadu 1790/5, Ostrava, 708 00, Czechia
A R T I C L E  I N F O
Keywords:
Uterine electromyography
Uterine activity monitoring
EHG signal processing
Uterine contractions detection
Term/preterm birth prediction
Pregnancy/labor classification

A B S T R A C T
Electrohysterography (EHG) represents a promising computational approach for non-invasive monitoring of
uterine activity during pregnancy and labor. This review summarizes the advancements in signal processing
techniques and machine learning algorithms that have been applied to enhance the utility of EHG. Key topics
include the extraction and analysis of uterine electrical signals, classification of contractions, and prediction
of obstetric outcomes such as preterm and labor/non-labor states. The review emphasizes computational
methodologies for signal proces

In [16]:
for name, text in papers.items():

    words = len(text.split())

    print(f"{name}: {words} words")

paper1: 24185 words
paper10: 3198 words
paper2: 11620 words
paper3: 4275 words
paper4: 8785 words
paper5: 8822 words
paper6: 6291 words
paper7: 17621 words
paper8: 4788 words
paper9: 5015 words

In [17]:
summary = []

for name, text in papers.items():

    summary.append({

        "Paper": name,

        "Words": len(text.split())

    })

In [18]:
import pandas as pd

summary_df = pd.DataFrame(summary)

summary_df

     Paper  Words
0   paper1  24185
1  paper10   3198
2   paper2  11620
3   paper3   4275
4   paper4   8785
5   paper5   8822
6   paper6   6291
7   paper7  17621
8   paper8   4788
9   paper9   5015

In [19]:
summary_df.sort_values("Words", ascending=False)

     Paper  Words
0   paper1  24185
7   paper7  17621
2   paper2  11620
5   paper5   8822
4   paper4   8785
6   paper6   6291
9   paper9   5015
8   paper8   4788
3   paper3   4275
1  paper10   3198

In [20]:
summary_df["Words"].sum()

np.int64(94600)

In [21]:
TEXT_PATH = PROJECT_PATH / "text"

TEXT_PATH.mkdir(exist_ok=True)

In [22]:
for name, text in papers.items():

    with open(TEXT_PATH / f"{name}.txt", "w", encoding="utf-8") as f:

        f.write(text)